FROM alpine:3.20

RUN apk add --no-cache postfix ca-certificates opendkim opendkim-utils

COPY mta-entrypoint.sh /usr/local/bin/mta-entrypoint.sh
RUN chmod +x /usr/local/bin/mta-entrypoint.sh

EXPOSE 10025
ENTRYPOINT ["/usr/local/bin/mta-entrypoint.sh"]
