import { and, eq, lte, or } from "drizzle-orm";
import { db, pool } from "../../src/db";
import { campaigns, contactLists, contacts, lists, messages } from "../../src/db/schema";
import { workerHeartbeats } from "../../src/db/operations-schema";
const intervalMs=Math.max(1000,Number(process.env.CAMPAIGN_WORKER_INTERVAL_MS||"5000"));
async function heartbeat(meta:Record<string,unknown>={}){await db.insert(workerHeartbeats).values({workerName:"campaign",metadata:meta}).onConflictDoUpdate({target:workerHeartbeats.workerName,set:{lastSeenAt:new Date(),metadata:meta}})}
async function runOnce(){const now=new Date();const due=await db.select().from(campaigns).where(or(eq(campaigns.status,"queued"),and(eq(campaigns.status,"scheduled"),lte(campaigns.scheduledAt,now)))).limit(10);let resolved=0;for(const campaign of due){if(!campaign.listId)continue;const [list]=await db.select().from(lists).where(eq(lists.id,campaign.listId)).limit(1);if(!list||list.isDynamic){if(list?.isDynamic)console.warn(`[campaign-worker] ${campaign.id}: dynamic list requires a persisted segment rule`);continue}const recipients=await db.select({contactId:contacts.id,email:contacts.email}).from(contactLists).innerJoin(contacts,eq(contactLists.contactId,contacts.id)).where(and(eq(contactLists.listId,campaign.listId),eq(contacts.status,"active")));if(recipients.length)await db.insert(messages).values(recipients.map(r=>({campaignId:campaign.id,contactId:r.contactId,recipientEmail:r.email,status:"queued" as const}))).onConflictDoNothing({target:[messages.campaignId,messages.contactId]});await db.update(campaigns).set({status:"sending",updatedAt:new Date()}).where(eq(campaigns.id,campaign.id));resolved+=recipients.length;console.log(`[campaign-worker] ${campaign.id}: resolved ${recipients.length} recipients`)}await heartbeat({state:"online",campaigns:due.length,resolved})}
async function main(){console.log("[campaign-worker] started");while(true){try{await runOnce()}catch(e){console.error("[campaign-worker]",e);await heartbeat({state:"error"}).catch(()=>{})}await new Promise(r=>setTimeout(r,intervalMs))}}
main().catch(console.error);process.on("SIGTERM",async()=>{await pool.end();process.exit(0)});
