import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { desc,eq,sql } from "drizzle-orm";
import { AppShell } from "@/components/app-shell";
import { MessageStatusBadge } from "@/components/message-status-badge";
import { ContactEditor,ContactTags } from "@/components/contact-editor";
import { db,databaseConfigured } from "@/db";
import { campaigns,contactTags,contacts,messageEvents,messages,tags } from "@/db/schema";
import { getSession } from "@/lib/auth";

const fmt=(d:Date|null|undefined)=>d?new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(d):"—";

export default async function ContactPage({params}:{params:Promise<{id:string}>}){
 const session=await getSession();if(!session)redirect("/login");if(!databaseConfigured)redirect("/contacts");const {id}=await params;
 const [contact]=await db.select().from(contacts).where(eq(contacts.id,id)).limit(1);if(!contact)notFound();
 const [tagRows,stats,campaignRows,eventRows,clickedRows]=await Promise.all([
  db.select({id:tags.id,name:tags.name}).from(contactTags).innerJoin(tags,eq(contactTags.tagId,tags.id)).where(eq(contactTags.contactId,id)),
  db.execute(sql`select count(*)::int messages,count(*) filter(where m.status='delivered')::int delivered,count(*) filter(where m.status='bounced')::int bounced,count(*) filter(where m.status='failed')::int failed,(select count(*)::int from message_events e join messages mm on mm.id=e.message_id where mm.contact_id=${id} and e.type='open' and coalesce((e.payload->>'qualified')::boolean,coalesce((e.payload->>'automated')::boolean,false)=false)=true) opens,(select count(distinct e.message_id)::int from message_events e join messages mm on mm.id=e.message_id where mm.contact_id=${id} and e.type='open' and coalesce((e.payload->>'qualified')::boolean,coalesce((e.payload->>'automated')::boolean,false)=false)=true) unique_opens,(select count(*)::int from message_events e join messages mm on mm.id=e.message_id where mm.contact_id=${id} and e.type='click' and coalesce((e.payload->>'qualified')::boolean,coalesce((e.payload->>'automated')::boolean,false)=false)=true) clicks,(select count(distinct e.message_id)::int from message_events e join messages mm on mm.id=e.message_id where mm.contact_id=${id} and e.type='click' and coalesce((e.payload->>'qualified')::boolean,coalesce((e.payload->>'automated')::boolean,false)=false)=true) unique_clicks,(select min(e.created_at) from message_events e join messages mm on mm.id=e.message_id where mm.contact_id=${id} and e.type='open' and coalesce((e.payload->>'qualified')::boolean,coalesce((e.payload->>'automated')::boolean,false)=false)=true) first_open,(select max(e.created_at) from message_events e join messages mm on mm.id=e.message_id where mm.contact_id=${id} and e.type='open' and coalesce((e.payload->>'qualified')::boolean,coalesce((e.payload->>'automated')::boolean,false)=false)=true) last_open,(select max(e.created_at) from message_events e join messages mm on mm.id=e.message_id where mm.contact_id=${id} and e.type='click' and coalesce((e.payload->>'qualified')::boolean,coalesce((e.payload->>'automated')::boolean,false)=false)=true) last_click from messages m where m.contact_id=${id}`),
  db.select({messageId:messages.id,campaignId:campaigns.id,campaignName:campaigns.name,subject:campaigns.subject,messageStatus:messages.status,queuedAt:messages.queuedAt,deliveredAt:messages.deliveredAt,lastError:messages.lastError}).from(messages).innerJoin(campaigns,eq(campaigns.id,messages.campaignId)).where(eq(messages.contactId,id)).orderBy(desc(messages.queuedAt)).limit(50),
  db.select({id:messageEvents.id,type:messageEvents.type,payload:messageEvents.payload,createdAt:messageEvents.createdAt,messageId:messageEvents.messageId}).from(messageEvents).innerJoin(messages,eq(messages.id,messageEvents.messageId)).where(eq(messages.contactId,id)).orderBy(desc(messageEvents.createdAt)).limit(150),
  db.execute(sql`select e.payload->>'url' url,count(*)::int clicks,min(e.created_at) first_click,max(e.created_at) last_click from message_events e join messages m on m.id=e.message_id where m.contact_id=${id} and e.type='click' and coalesce((e.payload->>'qualified')::boolean,coalesce((e.payload->>'automated')::boolean,false)=false)=true and nullif(e.payload->>'url','') is not null group by 1 order by clicks desc,last_click desc limit 30`)
 ]);
 const s=(stats.rows[0]||{}) as Record<string,unknown>;const clicked=clickedRows.rows as Record<string,unknown>[];const name=[contact.firstName,contact.lastName].filter(Boolean).join(" ")||contact.email;
 return <AppShell session={session}>
  <section className="premium-panel mb-6 overflow-hidden">
  <div className="bg-[radial-gradient(circle_at_top_right,rgba(109,93,252,.12),transparent_38%)] p-5 sm:p-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
      <div className="min-w-0">
        <p className="page-eyebrow">Audience 360</p>
        <h1 className="mt-1 break-words text-2xl font-black tracking-[-.035em] sm:text-3xl">{name}</h1>
        <p className="mt-2 break-all text-sm font-semibold text-[var(--muted)]">{contact.email}</p>
      </div>
      <div className="flex flex-wrap gap-2">
        <span className={`rounded-full px-2.5 py-1 text-xs font-extrabold capitalize ${contact.validationStatus==="accepted"||contact.validationStatus==="valid"?"bg-emerald-500/10 text-emerald-700 dark:text-emerald-300":contact.validationStatus==="invalid"?"bg-rose-500/10 text-rose-700 dark:text-rose-300":"bg-amber-500/10 text-amber-700 dark:text-amber-300"}`}>Validation · {contact.validationStatus}</span>
        <span className={`rounded-full px-2.5 py-1 text-xs font-extrabold capitalize ${contact.status==="active"?"bg-blue-500/10 text-blue-700 dark:text-blue-300":"bg-zinc-500/10 text-zinc-600 dark:text-zinc-300"}`}>{contact.status}</span>
      </div>
    </div>
    <div className="mt-5 grid gap-3 sm:grid-cols-3">
      <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)]/80 p-3.5"><div className="text-[10px] font-black uppercase tracking-[.12em] text-[var(--muted)]">Source</div><div className="mt-1 text-sm font-black capitalize">{contact.source.replaceAll("_"," ")}</div></div>
      <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)]/80 p-3.5"><div className="text-[10px] font-black uppercase tracking-[.12em] text-[var(--muted)]">Consent</div><div className={`mt-1 text-sm font-black capitalize ${contact.consentStatus==="confirmed"?"text-emerald-700 dark:text-emerald-300":"text-amber-700 dark:text-amber-300"}`}>{contact.consentStatus}</div></div>
      <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)]/80 p-3.5"><div className="text-[10px] font-black uppercase tracking-[.12em] text-[var(--muted)]">Opt-in source</div><div className="mt-1 text-sm font-black">{contact.consentSource||"Not recorded"}</div></div>
    </div>
  </div>
</section>
  <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Messages",Number(s.messages||0),`${Number(s.delivered||0)} delivered`],["Unique opens",Number(s.unique_opens||0),`${Number(s.opens||0)} total open events`],["Unique clicks",Number(s.unique_clicks||0),`${Number(s.clicks||0)} total clicks`],["Bounce / failed",Number(s.bounced||0)+Number(s.failed||0),`${Number(s.bounced||0)} bounced · ${Number(s.failed||0)} failed`]].map(([l,v,m])=><article key={String(l)} className="metric-card p-5"><p className="text-xs font-extrabold text-[var(--muted)]">{l}</p><p className="mt-3 text-3xl font-black">{Number(v).toLocaleString()}</p><p className="mt-1 text-xs text-[var(--muted)]">{String(m)}</p></article>)}</section>
  <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><ContactEditor contact={{id:contact.id,email:contact.email,firstName:contact.firstName,lastName:contact.lastName,status:contact.status,attributes:contact.attributes}}/><div className="space-y-5"><ContactTags contactId={contact.id} tags={tagRows}/><article className="premium-panel p-5"><h2 className="font-black">Engagement signals</h2><div className="mt-4 space-y-3 text-sm"><div><span className="text-[var(--muted)]">First observed open</span><b className="mt-1 block">{s.first_open?fmt(new Date(String(s.first_open))):"Never"}</b></div><div><span className="text-[var(--muted)]">Last observed open</span><b className="mt-1 block">{s.last_open?fmt(new Date(String(s.last_open))):"Never"}</b></div><div><span className="text-[var(--muted)]">Last verified click</span><b className="mt-1 block">{s.last_click?fmt(new Date(String(s.last_click))):"Never"}</b></div></div><p className="mt-4 text-xs leading-5 text-[var(--muted)]">Open tracking is an observed signal; email clients do not expose a reliable message-close event. Automated scanner events are excluded from these human metrics.</p></article></div></div>
  <section className="mt-5 grid gap-5 xl:grid-cols-2"><article className="premium-panel overflow-hidden"><div className="border-b border-[var(--border)] p-5"><h2 className="font-black">Campaign & delivery history</h2><p className="mt-1 text-xs text-[var(--muted)]">Every recent message resolved to this contact.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[var(--surface-soft)] text-[10px] font-black uppercase tracking-[.12em] text-[var(--muted)]"><tr><th className="px-5 py-3">Campaign</th><th>Status</th><th>Queued</th><th>Delivered</th><th>Detail</th></tr></thead><tbody>{campaignRows.length?campaignRows.map(x=><tr key={x.messageId} className="border-t border-[var(--border)]"><td className="px-5 py-3"><Link href={`/campaigns/${x.campaignId}`} className="font-bold hover:underline">{x.campaignName}</Link><div className="text-xs text-[var(--muted)]">{x.subject}</div></td><td><Link href={`/messages/${x.messageId}`} className="inline-block"><MessageStatusBadge status={x.messageStatus} compact /></Link></td><td className="text-xs text-[var(--muted)]">{fmt(x.queuedAt)}</td><td className="text-xs text-[var(--muted)]">{fmt(x.deliveredAt)}</td><td className="max-w-[220px] truncate text-xs text-rose-500" title={x.lastError||""}>{x.lastError||"—"}</td></tr>):<tr><td colSpan={5} className="p-8 text-center text-[var(--muted)]">No campaign history.</td></tr>}</tbody></table></div></article><article className="premium-panel overflow-hidden"><div className="border-b border-[var(--border)] p-5"><h2 className="font-black">Clicked links</h2><p className="mt-1 text-xs text-[var(--muted)]">Verified links this recipient actually interacted with.</p></div><div className="divide-y divide-[var(--border)]">{clicked.length?clicked.map(x=><div key={String(x.url)} className="flex items-start justify-between gap-4 p-4"><a href={String(x.url)} target="_blank" rel="noreferrer" className="min-w-0 break-all text-sm font-bold text-violet-600 hover:underline">{String(x.url)}</a><div className="shrink-0 text-right text-xs"><b>{Number(x.clicks||0)}×</b><div className="text-[var(--muted)]">{x.last_click?fmt(new Date(String(x.last_click))):"—"}</div></div></div>):<div className="p-8 text-center text-sm text-[var(--muted)]">No verified clicks yet.</div>}</div></article></section>
  <article className="premium-panel mt-5 overflow-hidden">
  <div className="border-b border-[var(--border)] p-5"><h2 className="font-black">Activity timeline</h2><p className="mt-1 text-xs text-[var(--muted)]">Human-readable activity first; technical payload stays available on demand.</p></div>
  <div className="divide-y divide-[var(--border)]">{eventRows.length?eventRows.map(e=>{
    const label=e.type.replaceAll("_"," ");
    const tone=e.type.includes("bounce")||e.type==="failed"?"bg-rose-500/10 text-rose-700 dark:text-rose-300":e.type.includes("deliver")||e.type==="open"||e.type==="click"?"bg-emerald-500/10 text-emerald-700 dark:text-emerald-300":"bg-blue-500/10 text-blue-700 dark:text-blue-300";
    return <div key={e.id} className="p-4 transition hover:bg-[var(--surface-soft)]"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase tracking-wide ${tone}`}>{label}</span><Link href={`/messages/${e.messageId}`} className="text-[11px] font-bold text-violet-600 hover:underline">View message</Link></div>{Object.keys(e.payload||{}).length?<details className="mt-2"><summary className="cursor-pointer text-xs font-bold text-[var(--muted)] hover:text-[var(--foreground)]">Technical details</summary><pre className="mt-2 max-h-56 overflow-auto whitespace-pre-wrap break-words rounded-xl border border-[var(--border)] bg-[var(--surface-soft)] p-3 font-mono text-[10px] leading-5 text-[var(--muted)]">{JSON.stringify(e.payload,null,2)}</pre></details>:<p className="mt-2 text-xs text-[var(--muted)]">No additional detail.</p>}</div><time className="shrink-0 text-[11px] text-[var(--muted)]">{fmt(e.createdAt)}</time></div></div>
  }):<div className="p-8 text-center text-sm text-[var(--muted)]">No activity recorded yet.</div>}</div>
</article>
 </AppShell>;
}
