import { ServerCog, Gauge, Mail } from "lucide-react";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ResourceCreate } from "@/components/resource-create";
import { db, databaseConfigured } from "@/db";
import { sendingAccounts } from "@/db/schema";
import { getSession } from "@/lib/auth";

export default async function InfrastructurePage() {
  const session = await getSession(); if (!session) redirect("/login");
  let rows: typeof sendingAccounts.$inferSelect[] = []; let dbError=false;
  if(databaseConfigured){try{rows=await db.select().from(sendingAccounts);}catch{dbError=true;}}
  const usable=databaseConfigured&&!dbError;
  return <AppShell session={session}>
    <div className="mb-7 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-extrabold uppercase tracking-[.18em] text-zinc-400">Sending</p><h1 className="text-3xl font-black tracking-[-.035em] sm:text-4xl">Infrastructure</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500 dark:text-zinc-400">Sending identities, Postfix transport, account-level limits and warm-up controls live here. Preview hosting does not pretend to run an MTA.</p></div><ResourceCreate disabled={!usable} endpoint="/api/resources/sending-accounts" title="Add sending account" buttonLabel="Add account" fields={[{name:"name",label:"Account name",required:true,placeholder:"Primary transactional"},{name:"fromName",label:"From name",required:true,placeholder:"NexiMail"},{name:"fromEmail",label:"From email",type:"email",required:true,placeholder:"mail@example.com"},{name:"replyTo",label:"Reply-to",type:"email",placeholder:"support@example.com"}]} /></div>
    <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
      <div className="premium-panel overflow-hidden">{rows.length?<div className="divide-y divide-zinc-100 dark:divide-zinc-900">{rows.map((row)=><article key={row.id} className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-violet-50 text-violet-600 dark:bg-violet-950/30 dark:text-violet-300"><Mail className="h-5 w-5" /></div><div><h2 className="font-black">{row.name}</h2><p className="mt-1 text-sm text-zinc-500">{row.fromName} &lt;{row.fromEmail}&gt;</p></div></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold capitalize text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300">{row.status}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-zinc-50 p-3 dark:bg-zinc-900"><span className="text-xs font-bold text-zinc-400">Hourly limit</span><div className="mt-1 font-black">{row.hourlyLimit.toLocaleString()}</div></div><div className="rounded-xl bg-zinc-50 p-3 dark:bg-zinc-900"><span className="text-xs font-bold text-zinc-400">Daily limit</span><div className="mt-1 font-black">{row.dailyLimit.toLocaleString()}</div></div></div></article>)}</div>:<div className="grid min-h-72 place-items-center p-8 text-center"><div><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-zinc-100 text-zinc-500 dark:bg-zinc-900"><ServerCog className="h-5 w-5" /></div><h2 className="mt-4 font-black">No sending accounts</h2><p className="mt-1 text-sm text-zinc-500">Add an identity after PostgreSQL is connected.</p></div></div>}</div>
      <aside className="premium-panel p-6"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-zinc-400">Transport policy</p><h2 className="mt-2 text-xl font-black">Postfix stays VPS-side</h2><p className="mt-3 text-sm leading-6 text-zinc-500 dark:text-zinc-400">Vercel is only a preview surface. Final transport, workers and SMTP listener remain self-hosted so the production architecture stays portable.</p><div className="mt-5 space-y-3">{[["Web requests","Never bulk-send"],["Queue","Worker controlled"],["MTA accepted","Not delivered"],["Remote 2xx","Delivered event"]].map(([a,b])=><div key={a} className="flex items-center justify-between rounded-xl border border-zinc-100 px-4 py-3 dark:border-zinc-800"><span className="text-sm font-bold">{a}</span><span className="text-xs font-bold text-zinc-400">{b}</span></div>)}</div><div className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-zinc-400"><Gauge className="h-4 w-4" /> Limits are stored per sending account</div></aside>
    </section>
  </AppShell>;
}
