import { Settings2, ShieldCheck } from "lucide-react";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ResourceCreate } from "@/components/resource-create";
import { db, databaseConfigured } from "@/db";
import { systemSettings } from "@/db/schema";
import { getSession } from "@/lib/auth";

export default async function SettingsPage() {
  const session=await getSession(); if(!session) redirect("/login");
  let rows: typeof systemSettings.$inferSelect[]=[]; let dbError=false;
  if(databaseConfigured){try{rows=await db.select().from(systemSettings);}catch{dbError=true;}}
  const usable=databaseConfigured&&!dbError;
  return <AppShell session={session}><div className="mb-7 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-extrabold uppercase tracking-[.18em] text-zinc-400">Workspace</p><h1 className="text-3xl font-black tracking-[-.035em] sm:text-4xl">Settings</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500 dark:text-zinc-400">Workspace defaults live in persistent storage. Infrastructure secrets remain environment variables and are never exposed in the UI.</p></div><ResourceCreate disabled={!usable||session.role!=="owner"} endpoint="/api/resources/settings" title="Save workspace setting" buttonLabel="Add setting" fields={[{name:"key",label:"Setting key",required:true,placeholder:"campaign.default_from_name"},{name:"value",label:"Value",required:true,placeholder:"NexiMail"}]} /></div><section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><article className="premium-panel overflow-hidden">{rows.length?<div className="divide-y divide-zinc-100 dark:divide-zinc-900">{rows.map((row)=><div className="flex flex-col gap-2 p-5 sm:flex-row sm:items-center sm:justify-between" key={row.key}><div><div className="font-mono text-sm font-bold">{row.key}</div><div className="mt-1 max-w-xl truncate text-xs text-zinc-500">{JSON.stringify(row.value)}</div></div><span className="text-xs font-bold text-zinc-400">{new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(row.updatedAt)}</span></div>)}</div>:<div className="grid min-h-64 place-items-center p-8 text-center"><div><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-zinc-100 text-zinc-500 dark:bg-zinc-900"><Settings2 className="h-5 w-5"/></div><h2 className="mt-4 font-black">No workspace overrides</h2><p className="mt-1 text-sm text-zinc-500">Defaults remain in code until an owner persists an override.</p></div></div>}</article><aside className="premium-panel p-6"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-50 text-emerald-600 dark:bg-emerald-950/30 dark:text-emerald-300"><ShieldCheck className="h-5 w-5"/></div><h2 className="mt-5 text-xl font-black">Security boundary</h2><p className="mt-2 text-sm leading-6 text-zinc-500 dark:text-zinc-400">SMTP passwords, database URLs, Redis URLs and signing secrets stay outside this table. Owner-only infrastructure actions will remain separately authorized.</p><div className="mt-5 rounded-xl border border-zinc-100 p-4 text-sm dark:border-zinc-800"><span className="font-bold">Signed in role:</span> <span className="capitalize text-zinc-500">{session.role}</span></div></aside></section></AppShell>;
}
